### ISSUE TITLE
Schema and tables not showing for SAP HANA

### ISSUE THREAD

**Issue by Lsubatin** [rickbergfalk/sqlpad#322] opened 2018-03-23 22:42 UTC
Hi, 

Even if creating a connection with a schema name and the right permissions, the left-side panel does not show the list of tables for a schema. 

![image](https://user-images.githubusercontent.com/24896969/37856258-4e1671b2-2ed2-11e8-8a19-2d635aef0d52.png)

![image](https://user-images.githubusercontent.com/24896969/37856250-39c3ba4e-2ed2-11e8-8445-f8f04d54ff32.png)

Thanks, 
Lucia.

**Comment by rickbergfalk** [comment] 2018-03-28 01:48
Thanks for reporting this @Lsubatin - I'll take a look into what might be going on.

**Comment by rickbergfalk** [comment] 2018-03-30 02:54
I pushed an update to npm and docker, 2.5.3. Please give that a try, and press the "reload" button on the schema sidebar to force a refresh of the schema. I'm able to see tables and columns with a test instance that was set up.

Let me know how it goes

**Comment by g3rv4** [comment] 2018-03-30 18:03
I'm having the same issue on a docker instance connecting to a docker instance of SQL Server. I'm seeing an ajax request to `/api/schema-info/tqyQyvPvq4QFRp6k` that never gets replied to.

I've tested that the connection works (that's what sqlpad says when adding it). Is there any more info I can get you? I'll try with an older version

**Comment by g3rv4** [comment] 2018-03-30 18:09
Version 2.5.1 works fine for me :D

**Comment by rickbergfalk** [comment] 2018-03-30 22:48
Thanks @g3rv4! Are you saying that 2.5.1 works for you, but 2.5.3 does not?

**Comment by g3rv4** [comment] 2018-03-30 23:33
@rickbergfalk that is correct! I’m running both sqlpad and sql server on docker containers in MacOS fwiw. On 2.5.3, it gets stuck. On 2.5.1, it works fine.

I may get to play with it on the weekend... nodejs is not my favorite language but sqlpad makes me want to play with it ;)

Would getting you a docker-compose.yml with a repto help you debug it?

**Comment by rickbergfalk** [comment] 2018-03-31 15:16
Interesting - I've noticed that api has issues in TravisCI (which runs in a docker environment), but it does not have issues when I run sqlpad locally. 

A docker-compose.yml that can reproduce the issue would be great! I haven't been able to reproduce it, and trying to debug the issue remotely via logs has been difficult.

**Comment by g3rv4** [comment] 2018-03-31 16:35
@rickbergfalk I've got a local repro. Here are the steps:

### Start both sql server and sqlpad containers.

I've done so with this `docker-compose.yml` (my folder is `sqlpadwithissues`, that's going to be relevant for the docker container names)

```
version: '2'
services:
  mssql:
    image: 'microsoft/mssql-server-linux:2017-latest'
    restart: always
    hostname: 'mssql'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperP4ssw0rd!
      - MSSQL_PID=Express
  sqlpad:
    image: 'sqlpad/sqlpad:2.5.3'
    hostname: 'sqlpad'
    ports:
      - '3000:3000'
```

### Create a database on the sql server instance

Connect to the database server (here is where the folder name is relevant)

```
docker exec -it sqlpadwithissues_mssql_1 /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P SuperP4ssw0rd!
```

Create the database

```
1> CREATE DATABASE LetsTestIt;
2> Go
```

### Connect to sqlpad, configure the connection and profit!

![GifWithTheIssue](https://gmc.uy/profitNotProfit.gif)

**Comment by rickbergfalk** [comment] 2018-03-31 17:25
@g3rv4 thanks for the repro! 

I feel like I'm going insane but this works for me. 

May I ask what operating system and docker version you are using? I'm on mac os 10.13.3, docker 18.03.0-ce-mac60 (23751). 

What's strange is I've narrowed it down to something related to the `cache` collection of the embedded database in use. Other collections work in docker, and all of it works when running sqlpad locally on mac.

**Comment by g3rv4** [comment] 2018-03-31 17:43
@rickbergfalk wow that's odd...

I'm on mac os 10.13.3 and docker Docker version 18.03.0-ce, build 0520e24... maybe the different docker version is causing this one? I've checked that I don't have pending updates

**Comment by rickbergfalk** [comment] 2018-03-31 17:52
@g3rv4 even more odd, now I'm experiencing the issue now that I'm trying it again. I don't know why it would have worked my first docker instance, but not the second.

I'm also not able to get a response from an adhoc query now that this behavior showed up. Is that a behavior you are experiencing as well?

**Comment by g3rv4** [comment] 2018-03-31 18:01
@rickbergfalk yes, I also got no responses when doing a query... everything works fine for me on 2.5.1

**Comment by rickbergfalk** [comment] 2018-03-31 18:49
I'm not 100% sure where the issue is but I think I have a good idea that it is related to the embedded database being wrapped in promises, and something wonky with the docker file system? 

Mounting the sqlpad data directory via volumes sees the issue during the first run. But then if you do `docker-compose down`, then `docker-compose up`, everything works as it should. 

Need to step away from this for a bit but will keep looking into it

**Comment by rickbergfalk** [comment] 2018-03-31 18:54
Here's the docker-compose.yml I was using for reference if anyone is interested https://github.com/rickbergfalk/sqlpad/blob/master/docker-validation/mssql/docker-compose.yml

**Comment by g3rv4** [comment] 2018-03-31 20:18
Interesting! I can also get the same thing to work even when not using volumes... that is, the exact same docker compose I shared earlier fails the first time but after a `stop` and an `up`, it works perfectly.

My guess is that there's something odd regarding what the db does when there's no file vs when there is one. In order to verify that I did the following:

* I started a new instance, set it up -> it failed (as expected)
* I stopped it, restarted it -> it worked (as expected)

Then I mounted `/var/lib/sqlpad` to a local folder.

* I started a new instance, set it up -> it failed (as expected)
* I stopped it, restarted it -> it worked (as expected)
* I removed the contents from my mounted folder
* I stopped it, restarted it -> it failed!

And then I tried with a brand new image but with the content from my previous run:

* I deleted the instance
* I started it with the same mounted folder. It worked the first time

Sooo... it seems to fail only when there are no files in the folder where the data is stored. Running the migrations -> closing the connection -> opening it again could be a quick hack to fix it.

**Comment by rickbergfalk** [comment] 2018-03-31 20:51
This explains why I've never come across this locally. the tests never test
an initial setup/migration sequence.

I think I've pinpointed the problem. I'll aim to have the fix published
tomorrow

**Comment by rickbergfalk** [comment] 2018-04-01 04:34
I'm fairly certain I've addressed this issue. A fix has been published under version 2.5.4 available on both npm and docker hub. Let me know how it works out.

Thanks for reporting this @Lsubatin and all the assistance tracking this down @g3rv4!

**Comment by g3rv4** [comment] 2018-04-01 14:06
@rickbergfalk \o/ effectively, it's working as expected on first run now, thanks a ton!

**Comment by rickbergfalk** [comment] 2018-04-01 19:48
Great to hear and you're welcome!

**Closed by rickbergfalk** 2018-04-01 19:48 UTC

**Comment by Lsubatin** [comment] 2018-04-11 00:49
Thank you very much, Rick! Sorry I did not reply earlier. Thanks for the fix!
