### ISSUE TITLE
When opening pre-saved query sqlpad transitions into new query

### ISSUE THREAD

**Issue by Chumbaloo** [rickbergfalk/sqlpad#369] opened 2018-05-28 04:13 UTC
When clicking on a saved query, the saved query briefly opens up and then within a second transitions into the new query page. 

This is on version 2.6.0

**Comment by rickbergfalk** [comment] 2018-05-29 02:05
Hi Chumbaloo - How did you install SQLPad (npm, docker, or build from repo)?

Could I get the browser and version you are using as well?

**Comment by Chumbaloo** [comment] 2018-05-29 02:34
Hey @rickbergfalk, I installed SQLPad via npm.
Running on Ubuntu 16.04 server. 

Its repeatable on firefox 60.0.1 (64-bit) and google chrome (66.0.3359.181) (64-bit).
Let me know if you need more information.

**Comment by milutt** [comment] 2018-06-07 10:18
I have the same issue with firefox 60.0.1 (32-bit) and chrome 63.0.3239.132 (32-bit). It works fine with IE11. SQLPad 2.6.0 installed on Fedora 27 via npm.

**Comment by rickbergfalk** [comment] 2018-06-07 10:53
Thanks both for the info. I'll see if I can reproduce the issue and figure out what is going on.

**Comment by 22222** [comment] 2018-06-07 17:14
It looks like the problem is that after the connections load from an ajax call, the original (new) query is set back to the state.  So this issue happens if the "connections" endpoint takes longer to load than the "queries" endpoint.   That means it's easier to reproduce if you have a lot of available connections.

**Comment by rickbergfalk** [comment] 2018-06-07 20:37
Thanks for looking into this @22222! It looks like you already have a fix committed in your branch. Were you planning on opening a pull request?

**Comment by 22222** [comment] 2018-06-07 21:44
Yes, sorry for the delay, I wanted to do a little testing before I created the pull request.  Should be ready for review now in #370.

**Comment by rickbergfalk** [comment] 2018-06-17 14:51
This fix has been published to npm/docker under version 2.6.1

**Closed by rickbergfalk** 2018-06-17 14:51 UTC
