### ISSUE TITLE
invalid SQL generates (Javascript) TypeError: Cannot destructure property `rows` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by clach04** [rickbergfalk/sqlpad#492] opened 2019-12-06 22:36 UTC
Seen with an older version (3.0.2), I need to test with headrevs. Recording information I have to hand now.

Invalid SQL, for example a truncated SELECT:

    SELECT

Results in error in the results pane:

    TypeError: Cannot destructure property `rows` of 'undefined' or 'null'.

This is with https://github.com/rickbergfalk/sqlpad/wiki/ODBC - I also need to test with another driver.

**Comment by clach04** [comment] 2019-12-11 17:39
Works fine with other drivers, looks like a bug in the error handling for UnixODBC.

**Comment by rickbergfalk** [comment] 2020-02-29 03:14
@clach04 I think this may have been resolved when the implementation was updated for the odbc v2 as I'm unable to reproduce.

Could you verify with latest version of SQLPad by chance?

**Comment by MuchAdoAboutNothing** [comment] 2020-03-02 20:23
This seems to have been fixed - It now gives a generic error "Error: [odbc] Error executing the sql statement"

**Comment by rickbergfalk** [comment] 2020-03-02 20:53
@MuchAdoAboutNothing I recently discovered that too, and have that (hopefully) fixed in https://github.com/rickbergfalk/sqlpad/pull/560.

**Comment by rickbergfalk** [comment] 2020-04-06 18:17
There's been another round of fixes on this for #598. Depending on the odbc driver used, the node odbc lib may not return an expected result. Hopefully this is fixed with this latest change. If not we can reopen. (I'm unable to reproduce with odbc and sqlite odbc drive)

**Closed by rickbergfalk** 2020-04-06 18:17 UTC
Labels: bug

**Comment by clach04** [comment] 2020-12-17 18:56
Turned out to be a node-odbc bugm resolved in https://github.com/gordonthorpe/node-odbc/tree/odbc-errmsg
