### ISSUE TITLE
Cannot type on query textarea

### ISSUE THREAD

**Issue by CrashLaker** [rickbergfalk/sqlpad#446] opened 2019-07-05 13:29 UTC
Hi all,

I just started using sqlpad from commit https://github.com/rickbergfalk/sqlpad/commit/a27f6c9f09c2315c87a33def5352a24428079ff5

I noticed that sometimes I cannot type on the textarea which leaves me to usually press <Esc> multiple times or clicking at multiple areas and back to the textarea for it to work.

Anyone else having this issue?

**Comment by rickbergfalk** [comment] 2019-07-05 22:16
Hi @CrashLaker - I've had this issue in the past after scrolling or interacting with the result grid. Have you noticed a particular series of events that can reproduce this issue?

**Comment by rickbergfalk** [comment] 2019-07-05 22:36
I've added the old workaround back in https://github.com/rickbergfalk/sqlpad/commit/d8d75bb7bc240ff0fd3adcfd651426afa3284515 as I was able to reproduce the old behavior.

Want to see if that fixes the issue you're seeing as well?

**Comment by CrashLaker** [comment] 2019-07-05 23:00
Hi @rickbergfalk 

thank you for your reply.

I noticed that this happens when the query result has many columns and you scroll the bottom frame horizontally so that It dynamically render some more columns then when I go back to the textarea it gets stuck.

So I just click randomly and press many <Esc>s to "fix" it.

Ok. Imma try https://github.com/rickbergfalk/sqlpad/commit/d8d75bb7bc240ff0fd3adcfd651426afa3284515

**Comment by CrashLaker** [comment] 2019-07-05 23:05
Still getting stuck with https://github.com/rickbergfalk/sqlpad/commit/d8d75bb7bc240ff0fd3adcfd651426afa3284515

:(

**Comment by CrashLaker** [comment] 2019-07-17 19:32
I also cannot type when the query return an error

**Comment by rickbergfalk** [comment] 2019-08-07 04:16
I added another workaround to hopefully address the freezing after query error. Would you be able to check and see if things are fixed for you in latest master? 

If anyone out there has any ideas as to why this is happening I'd love to find out. The solution in place now is quite a hacky one.

**Comment by rickbergfalk** [comment] 2019-09-15 03:39
Closing this since I haven't reproduced since last fix (even for query error)

**Closed by rickbergfalk** 2019-09-15 03:39 UTC
