### ISSUE TITLE
Host reboot causes loss of queries

### ISSUE THREAD

**Issue by mupaneu** [rickbergfalk/sqlpad#416] opened 2019-03-15 12:40 UTC
Customer runs Sqlpad for internal use on a LAN only Windows 2012 r2 box. For stability reasons I defined a Windows service with nssm.exe running SQLPad with Windows start.

Now when the Windows server host is rebooted by system or admin for maintenance reasons, mostly Microsoft updates, users report that some of their saved queries got lost. How to avoid this? Instruct admin to shut down SQLpad manually first? If so, how best? Stop Windows service? Or is there any npm consolidation / transaction commit command?

**Comment by rickbergfalk** [comment] 2019-03-15 14:11
There is no commit command, but that shouldn't be necessary. Under the hood SQLPad uses an in-memory javascript database that appends to a file on disk. If there was data loss, perhaps something happened during a file compaction and some of the file became corrupted? https://github.com/louischatriot/nedb#persistence

Under normal circumstances I haven't seen data loss, but my use of SQLPad is kind ad-hoc and run locally on an as needed basis.

I'd maybe recommend taking a backup of the SQLPad db directory? The database files are text/json documents and it should be okay to do while SQLPad is running.

Separately, it is possible to run and work on a query, and never save it... and then lose it if the server goes down. It has happened to me before, and I'm contemplating saving un-saved queries client-side for those cases.

Hope this helps! 

If you can reproduce this issue in a test environment let me know and it can be explored futher

**Comment by mupaneu** [comment] 2019-03-15 15:39
Thank you. I am sure this helps. I always prefer a text backup for such configuration data. Does the db also cache the not-saved queries?

**Comment by rickbergfalk** [comment] 2019-03-15 15:46
Unfortunately the not-yet-saved queries will not be in the cache or the db. I've been wanting to add query history (for even unsaved queries) to SQLPad, but before thats brought in I need to migrate to a different database solution, as the current db is an in-memory one.

**Comment by mupaneu** [comment] 2019-03-15 16:05
Don't worry, a history would resp. will just be a comfort feature IMHO. And a local backup of whatever I send to a web service by whatever interface is one of my rules anyway.

**Comment by bruth** [comment] 2020-04-21 20:16
I had a user report data loss for saved queries. SQLPad has been running for eight days.. and the `users.db` file appears to be populated correctly, but the `queries.db` file is empty. I have another instance running roughly the same period of time and those saved queries are still there.. I am not sure what is going on or how I could debug this? @rickbergfalk Any suggestions? Anything in the logs that could indicate the root cause?

**Comment by rickbergfalk** [comment] 2020-04-21 21:38
@bruth I'm not sure to be honest. Looking through the nedb repo for open issues might be best bet.

There is mention of auto compaction removing corrupt documents? I haven't run into that personally, but I wonder if that is at play https://github.com/louischatriot/nedb#persistence. 

I'll hopefully have the migration to sqlite ready early next week which should be a more robust option.

Maybe as a temporary safety measure auto-compaction for nedb is turned off?

**Comment by bruth** [comment] 2020-04-22 11:09
Thanks. Is there a way to disable auto-compaction through SQLPad configuration? Or a file to patch in a branch to try it out?

> I'll hopefully have the migration to sqlite ready early next week which should be a more robust option.

Very much looking forward to this.

**Comment by rickbergfalk** [comment] 2020-04-23 00:44
No configuration to disable auto-compaction, but commenting out this line here should do it https://github.com/rickbergfalk/sqlpad/blob/master/server/lib/db.js#L128

**Comment by bruth** [comment] 2020-04-23 01:39
Thanks.

**Comment by rickbergfalk** [comment] 2020-07-04 16:21
This should be resolved in v5 (or last month or so of `latest` docker hub image). 

SQLite is not used instead of the embedded JSON database, and there are options to use an external backend database as well (SQL Server, PostgreSQL, MySQL, MariaDB).

**Closed by rickbergfalk** 2020-07-04 16:21 UTC

**Comment by eladeyal-intel** [comment] 2020-07-04 16:25
SQLite is not used ==> SQLite is **now** used :-)
