### ISSUE TITLE
Running sqlpad returns error 

### ISSUE THREAD

**Issue by tooler** [rickbergfalk/sqlpad#224] opened 2017-09-07 01:54 UTC
Hi Rick and team,

Running the following command on ubuntu returns an error: sudo sqlpad --dir ./sqlpad/ --port 3000 --passphrase pass --save

Output:
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/sqlpad/routes/connections.js:2:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

Could you suggest a way forward? Thanks in advance.

**Comment by rickbergfalk** [comment] 2017-09-07 12:31
Hi @tooler - May I ask what version of node, npm, and sqlpad you are using? You can find this out by running

```sh
sqlpad -v
npm -v
node -v
```

SQLPad 2.x requires at least node 6.

**Comment by rickbergfalk** [comment] 2017-10-08 16:12
Hi @tooler - I'm going to close this issue out since I can't reproduce. If you're still facing this issue please let me know and we can reopen

**Closed by rickbergfalk** 2017-10-08 16:12 UTC
