### ISSUE TITLE
app crashed when export as .xlsx or .csv

### ISSUE THREAD

**Issue by john5480** [rickbergfalk/sqlpad#105] opened 2016-06-15 08:22 UTC
I've used sqlpad for months, it suddenly crashed this afteroon when I export some sql results as xlsx or csv format.
Here is the wrong info:

> http.js:733
      throw new TypeError('The header content contains invalid characters');
      ^
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (http.js:733:13)
    at /usr/local/sqlpad-master/routes/download-results.js:47:25
    at newArguments.(anonymous function) (/usr/local/sqlpad-master/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/usr/local/sqlpad-master/node_modules/nedb/lib/datastore.js:518:14)
    at callback (/usr/local/sqlpad-master/node_modules/nedb/lib/cursor.js:126:19)
    at /usr/local/sqlpad-master/node_modules/nedb/lib/cursor.js:193:12
    at /usr/local/sqlpad-master/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/usr/local/sqlpad-master/node_modules/nedb/node_modules/async/lib/async.js:130:20)
    at /usr/local/sqlpad-master/node_modules/nedb/lib/datastore.js:323:11
    at fn (/usr/local/sqlpad-master/node_modules/nedb/node_modules/async/lib/async.js:582:34)
[nodemon] app crashed - waiting for file changes before starting...

It seems the column including Chinese character  lead to the crash, but without Chinese it won't help neither, even we had exported Chinese column reports before.
Just suddenly sqlpad goes wrong, could you help with this?  Thks

**Comment by rickbergfalk** [comment] 2016-06-18 01:45
Hi @john5480. Thanks for the bug report. May I ask what version of nodejs and sqlpad you are using?

I'm currently on vacation but I'll look into this when I return.

**Comment by john5480** [comment] 2016-06-20 06:19
![qq 20160620141634](https://cloud.githubusercontent.com/assets/14275178/16184773/a15fea7c-36f1-11e6-834c-c57ce7470402.png)

# grep version *
package.json:  "version": "1.15.0",

here is the version of nodejs and sqlpad

**Comment by john5480** [comment] 2016-06-20 06:23
we got another sqlpad server to run the same version of nodejs and sqlpad , it just runs OK, that's so  weired

**Comment by rickbergfalk** [comment] 2016-06-27 14:44
I'm not sure what the culprit might be exactly since you were able to run another sqlpad instance successfully. Node.js 0.10.x is quite old though. Would it be possible for you to upgrade to version 4.x.x?

**Comment by rickbergfalk** [comment] 2016-06-29 22:33
Since another instance has run successfully and I can't reproduce the issue I'm going to close this issue. Please feel free to continue to keep it updated should this problem arise though.

**Closed by rickbergfalk** 2016-06-29 22:33 UTC

**Comment by john5480** [comment] 2016-06-30 01:54
our another instance face the same problem now, there's no instance we got here.
The first instance has been used for several weeks, the 2nd has been used for 10 days maybe.
We'll try updating the nodejs version to test.
Thks
